apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HivelocityMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      type: "${HIVELOCITY_WORKER_MACHINE_TYPE}"
      imageName: "ubuntu-22.04"
