kind: HivelocityMachineTemplate
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
metadata:
  name: "${CLUSTER_NAME}-control-plane"
spec:
  template:
    spec:
      deviceSelector:
        matchLabels:
          deviceType: ${HIVELOCITY_CONTROL_PLANE_DEVICE_TYPE}
      imageName: "ubuntu-22.04"
