apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: HivelocityMachineTemplate
metadata:
  name: "${CLUSTER_NAME}-md-0"
spec:
  template:
    spec:
      deviceSelector:
        matchLabels:
          deviceType: ${HIVELOCITY_WORKER_DEVICE_TYPE}
      imageName: "ubuntu-22.04"
