apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: HivelocityCluster
metadata:
  name: "${CLUSTER_NAME}"
spec:
  controlPlaneEndpoint:
    host: ""
    port: 443
  controlPlaneRegion: "${HIVELOCITY_REGION}"
  hivelocitySecretRef:
    name: hivelocity
    key: hivelocity
  sshKey:
    name: example-name
