# permissions for end users to view hivelocitymachinetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hivelocitymachinetemplate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-provider-hivelocity
    app.kubernetes.io/part-of: cluster-api-provider-hivelocity
    app.kubernetes.io/managed-by: kustomize
  name: hivelocitymachinetemplate-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - hivelocitymachinetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - hivelocitymachinetemplates/status
  verbs:
  - get
