name: "Setup Go"
description: "Setup Go"
runs:
  using: "composite"
  steps:
    - name: Install go
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        go-version-file: "go.mod"
        cache: true
        cache-dependency-path: go.sum
    - id: go-cache-paths
      shell: bash
      run: |
        echo "gobuild=$(go env GOCACHE)" >> $GITHUB_OUTPUT
        echo "gomod=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
    - name: Go Mod Cache
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
      with:
        path: ${{ steps.go-cache-paths.outputs.gomod }}
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-
    - name: Go Build Cache
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
      with:
        path: ${{ steps.go-cache-paths.outputs.gobuild }}
        key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-build-
