name: builder image workflow

on:
  push:
    branches:
      - 'main'
    paths:
      - ".github/workflows/builder-image.yml"
      - "images/builder/Dockerfile"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: hivelocity
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./images/builder/Dockerfile
          push: true
          tags: ghcr.io/hivelocity/caphv-builder:0.1.0
