name: E2E Basic (Manual)
on:
  workflow_dispatch:
env:
  IMAGE_NAME: caphv-staging
  REGISTRY: ghcr.io/hivelocity
  metadata_flavor: latest=false
  metadata_tags: type=sha
  registry_password: ${{ secrets.GITHUB_TOKEN }}
jobs:
  manager-image:
    name: Build and push manager image (e2e basic)
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Build and push manager image (e2e basic step)
        id: manager-image
        uses: ./.github/actions/manager-image

  test-release:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Test Release
        id: manager-image
        uses: ./.github/actions/test-release

  e2e-basic:
    name: Test e2e Basic
    concurrency: ci-${{ github.ref }}-e2e-basic
    runs-on: ubuntu-latest
    needs:
      - manager-image
      - test-release
    steps:
      - name: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Run e2e Test
        id: e2e
        uses: ./.github/actions/e2e
        with:
          e2e_name: basic
          e2e_make_target: test-e2e
          e2e_hivelocity_token: ${{ secrets.HIVELOCITY_API_KEY }}
