name: Check PR Markdown links

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    paths:
      - '**.md'

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # tag=v3.2.0
      - uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec # tag=1.0.15
        with:
          use-quiet-mode: 'yes'
          config-file: .markdownlinkcheck.json
          check-modified-files-only: 'yes'
          base-branch: main
          folder-path: docs/
