name: golangci-lint
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - "releases/**"
    paths:
      - "**.go"
      - "**go.mod"
      - "**go.sum"
      - "!tilt_modules/**"
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: v1.49.0 # https://github.com/golangci/golangci-lint/releases
          working-directory: ${{matrix.working-directory}}
