name: unit-test
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - "releases/**"
    paths:
      - "**.go"
      - "**go.mod"
      - "**go.sum"
jobs:
  test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19"
      - name: Test
        run: make test-unit
