name: Verify Pull Request
on: # yamllint disable-line rule:truthy
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]
# yamllint disable rule:line-length
jobs:
  pr-verify:
    runs-on: ubuntu-latest
    name: Verify Pull Request
    if: github.event_name != 'pull_request_target' || !github.event.pull_request.draft
    steps:
      - name: Verifier action
        id: verifier
        uses: kubernetes-sigs/kubebuilder-release-tools@4f3d1085b4458a49ed86918b4b55505716715b77 # v0.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Verify Boilerplate
        run: make verify-boilerplate

      - name: Verify Modules
        run: make verify-modules

      - name: Verify gen
        run: make verify-gen

      - name: Verify Shellcheck
        run: make verify-shellcheck

      - name: Verify Starlark
        run: make verify-starlark

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: "18"
      - name: Install renovate
        run: npm i -g renovate@35.54.0 # TODO update this via renovatebot
      - name: Validate config
        run: renovate-config-validator
        env:
          RENOVATE_CONFIG_FILE: .github/renovate.json5
      - name: Validate config
        run: renovate-config-validator
        env:
          RENOVATE_CONFIG_FILE: .github/renovate/approval.json5
      - name: Validate config
        run: renovate-config-validator
        env:
          RENOVATE_CONFIG_FILE: .github/renovate/commitMessage.json5
      - name: Validate config
        run: renovate-config-validator
        env:
          RENOVATE_CONFIG_FILE: .github/renovate/golang.json5
      - name: Validate config
        run: renovate-config-validator
        env:
          RENOVATE_CONFIG_FILE: .github/renovate/groups.json5
      - name: Validate config
        run: renovate-config-validator
        env:
          RENOVATE_CONFIG_FILE: .github/renovate/labels.json5
      - name: Validate config
        run: renovate-config-validator
        env:
          RENOVATE_CONFIG_FILE: .github/renovate/regexManagers.json5

      - name: Generate Token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1
        id: generate-token
        with:
          app_id: ${{ secrets.HIVELOCITY_APP_ID }}
          private_key: ${{ secrets.HIVELOCITY_APP_PRIVATE_KEY }}
      - name: Generate Size
        uses: pascalgn/size-label-action@37a5ad4ae20ea8032abf169d953bcd661fd82cd3 # v0.5.0
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          sizes: >
            {
            "0": "XS",
            "20": "S",
            "50": "M",
            "200": "L",
            "800": "XL",
            "2000": "XXL"
            }
      - name: Generate Labels
        uses: actions/labeler@9fcb2c2f5584144ca754f8bfe8c6f81e77753375 # v4
        with:
          configuration-path: .github/labeler.yaml
          repo-token: ${{ steps.generate-token.outputs.token }}
      - name: Sync Labels
        uses: EndBug/label-sync@da00f2c11fdb78e4fae44adac2fdd713778ea3e8 # v2
        with:
          config-file: .github/labels.yaml
          token: ${{ steps.generate-token.outputs.token }}
