name: Verify PR Code
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - "releases/**"
    paths-ignore:
      - "**.md"

jobs:
  verify-code:
    name: Verify Code
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19"
      - name: Verify Boilerplate
        run: make verify-boilerplate
      - name: Verify Modules
        run: make verify-modules
      - name: Verify gen
        run: make verify-gen
