name: Verify Pull Request
on: # yamllint disable-line rule:truthy
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]
# yamllint disable rule:line-length
jobs:
  pr-verify:
    runs-on: ubuntu-latest
    name: Verify Pull Request
    if: github.event_name != 'pull_request_target' || !github.event.pull_request.draft
    steps:
      - name: Verifier action
        id: verifier
        uses: kubernetes-sigs/kubebuilder-release-tools@4f3d1085b4458a49ed86918b4b55505716715b77 # v0.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Verify Boilerplate
        run: make verify-boilerplate

      # Does not work: https://github.com/hivelocity/cluster-api-provider-hivelocity/actions/runs/5612111752/job/15205124670?pr=102#step:6:84
      # ./hack/golang-modules-update.sh
      # go: could not create module cache: mkdir /go/pkg/mod: permission denied
      # - name: Verify Modules
      #   run: make verify-modules

      - name: Verify gen
        run: make verify-gen

      - name: Verify Shellcheck
        run: make verify-shellcheck

      - name: Verify Starlark
        run: make verify-starlark

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3
        with:
          node-version: "18"
