name: Caphv Image Cache Cleaner
# yamllint disable rule:line-length
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    # Run the GC on the first day in the month at 6am
    - cron: "0 6 1 * *"
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true
jobs:
  cache-cleaner:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - name: symin
    steps:
      # Load Golang cache build from GitHub
      - name: Load Caphv Golang cache build from GitHub
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        id: cache
        with:
          path: /tmp/.cache/caphv
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-caphv-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-caphv-
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-
            ${{ runner.os }}-go-
      - name: Create Caphv cache directory
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          mkdir -p /tmp/.cache/caphv
      # Clean docker's golang's cache
      - name: Clean Caphv Golang cache from GitHub
        shell: bash
        run: |
          rm -f /tmp/.cache/caphv/go-build-cache.tar.gz
          rm -f /tmp/.cache/caphv/go-pkg-cache.tar.gz
